# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6efa445f875b11460d2ead364a899633179229cd9ea8dfc8e266d20f78f1f322cd665cee909c8b96501ed3b17ee25cd81acddcfae9115d19d6e4387bfd47aba4

test:
  secret_key_base: f59935bfc7b25c8a017721b1ef10fa8d32b346bcfe4090e0b331a3fc336f4f35fa788a97de88998b76dfc267eddad35916d6167a7528fe104e522c35b9ab918c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
